rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
before_install:
  - gem update --system
  - gem update bundler
  - gem cleanup bundler
install: "bundle install --jobs 8"
script: "bundle exec rake"

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

sudo: false
cache: bundler
